SUPABASE_URL = "https://btvsumiwaykzvtxmgprk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0dnN1bWl3YXlrenZ0eG1ncHJrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQ2NTI4MCwiZXhwIjoyMDg0MDQxMjgwfQ.Ecf9lBccfSQhtHx-7kCt-0s-hGfJ6gv9kV1O-HFVFWA"
ADMIN_ACCESS_CODE = "YAS$laim"

yasico-tnc-salary_password = "yasico-tnc$"
